version: "3"

services:
  #MongoDB
  mongo_db:
    container_name: database_container-2
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  app:
    build: .
    ports:
      - 3003:3000
    environment:
      PORT: 3000
      DB_URL: mongodb+srv://nipunikumudika:nipunikumudika@cluster0.txmga7v.mongodb.net/JobBoard?retryWrites=true&w=majority

    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
#run command
# docker compose up
