version: "3"

services:
  # MongoDB
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile # Points to the Dockerfile in the root directory
    ports:
      - "3001:3000"
    environment:
      PORT: 3000
      DB_URL: mongodb+srv://nipunikumudika:nipunikumudika@cluster0.txmga7v.mongodb.net/JobBoard?retryWrites=true&w=majority
    depends_on:
      - mongo_db
      - match
    volumes:
      - .:/app # Bind the entire root directory to /app in the container

  match:
    build:
      context: ./match
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - ./match:/app # Bind the match directory to /app in the container

volumes:
  mongo_db:
